name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: http://localhost:8181/job/Secops-docker
      with:
        url: " http://localhost:8181/user/admin/"
        user: "/user/admin"
        token: “115007be2fd14a7cf977345eaab88c9011”
        job: "foobar"

