name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: isaacdevsecops/jenkins-action@master
      with:
        url: "http://localhost:8181/job/Devsecops-versioning/"
        user: "/user/admin"
        token: “115007be2fd14a7cf977345eaab88c9011”
        job: "Pipeline Devsecops-versioning"

